version: '3.8'

services: 
  web:
    build: .
    command: python3 manage.py runserver 127.0.0.1:8000
    volumes: 
      - .:/app
    ports: 
      - 8000:8000
    image: web:app
    container_name: foxxl_container
    command: python3 manage.py runserver 0.0.0.0:8000
